/* Auto-generated by slice types generate. Do not edit manually. */

export interface AboutSectionProps {
  [key: string]: unknown;
}

export interface AnimationsProps {
  [key: string]: unknown;
}

export interface AnimationsProviderProps {
  [key: string]: unknown;
}

export interface BackgroundAudioToggleProps {
  [key: string]: unknown;
}

export interface BadgeCarouselProps {
  [key: string]: unknown;
  accentColor?: string;
  autoPlay?: boolean;
  badges?: unknown[];
  borderRadius?: string;
  marqueeSpeed?: number;
  primaryColor?: string;
  secondaryColor?: string;
  shadow?: boolean;
  showControls?: boolean;
  title?: string;
}

export interface BuiltWithBadgeProps {
  [key: string]: unknown;
}

export interface ButtonProps {
  [key: string]: unknown;
  audioOnClickEnabled?: boolean;
  customColor?: Record<string, unknown>;
  icon?: Record<string, unknown>;
  onClickCallback?: (...args: unknown[]) => unknown;
  value?: string;
}

export interface CardProps {
  [key: string]: unknown;
  actions?: unknown[];
  badge?: string;
  customColor?: Record<string, unknown>;
  details?: string;
  disabled?: boolean;
  icon?: Record<string, unknown>;
  image?: string;
  interactive?: boolean;
  isOpen?: boolean;
  loading?: boolean;
  onClick?: (...args: unknown[]) => unknown;
  progress?: number;
  text?: string;
  title?: string;
  variant?: 'default' | 'elevated' | 'outlined' | 'minimal';
}

export interface CategoryManagerModalProps {
  [key: string]: unknown;
  categories?: Record<string, unknown>;
}

export interface CertificateCardProps {
  [key: string]: unknown;
}

export interface ChartsProps {
  [key: string]: unknown;
}

export interface CheckboxProps {
  [key: string]: unknown;
  checked?: boolean;
  customColor?: string;
  disabled?: boolean;
  label?: string;
  labelPlacement?: string;
}

export interface ClickSoundToggleProps {
  [key: string]: unknown;
}

export interface CodeVisualizerProps {
  [key: string]: unknown;
}

export interface ConfirmationModalProps {
  [key: string]: unknown;
}

export interface DetailsProps {
  [key: string]: unknown;
  text?: string;
  title?: string;
}

export interface DomPurifyProps {
  [key: string]: unknown;
}

export interface DropDownProps {
  [key: string]: unknown;
  label?: string;
  options?: unknown[];
}

export interface EducationSectionProps {
  [key: string]: unknown;
}

export interface ElementCarrouselProps {
  [key: string]: unknown;
}

export interface ExperienceCardProps {
  [key: string]: unknown;
}

export interface ExperienceSectionProps {
  [key: string]: unknown;
}

export interface FetchManagerProps {
  [key: string]: unknown;
}

export interface GameFlowProps {
  [key: string]: unknown;
  category?: string;
  imposters?: unknown[];
  names?: unknown[];
  word?: string;
}

export interface GameSetupProps {
  [key: string]: unknown;
  keepPlayers?: boolean;
  savedNames?: unknown[];
}

export interface GridProps {
  [key: string]: unknown;
  centerItems?: boolean;
  columns?: number;
  items?: unknown[];
  rows?: number;
}

export interface IconProps {
  [key: string]: unknown;
  color?: string;
  iconStyle?: string;
  name?: string;
  size?: string;
}

export interface ImageProps {
  [key: string]: unknown;
}

export interface ImageCarrouselProps {
  [key: string]: unknown;
  autoplay?: boolean;
  autoplaySpeed?: number;
  images?: unknown[];
  showIndicators?: boolean;
  showNavigation?: boolean;
}

export interface ImageDemoProps {
  [key: string]: unknown;
}

export interface ImposterGameContextServiceProps {
  [key: string]: unknown;
}

export interface IndexedDbManagerProps {
  [key: string]: unknown;
}

export interface InputProps {
  [key: string]: unknown;
  conditions?: Record<string, unknown>;
  disabled?: boolean;
  min?: string;
  placeholder?: string;
  required?: boolean;
  secret?: boolean;
  type?: 'text' | 'password' | 'email' | 'number' | 'search' | 'tel' | 'url';
  value?: string;
}

export interface LayoutProps {
  [key: string]: unknown;
  layout?: Record<string, unknown>;
  view?: Record<string, unknown>;
}

export interface LinkProps {
  [key: string]: unknown;
  classes?: string;
  path?: string;
  text?: string;
}

export interface LoadingProps {
  [key: string]: unknown;
  isActive?: boolean;
}

export interface LocalStorageManagerProps {
  [key: string]: unknown;
}

export interface MainMenuProps {
  [key: string]: unknown;
}

export interface MultiRouteProps {
  [key: string]: unknown;
}

export interface MyNavigationProps {
  [key: string]: unknown;
}

export interface NameManagerModalProps {
  [key: string]: unknown;
  lists?: unknown[];
}

export interface NavbarProps {
  [key: string]: unknown;
}

export interface NotFoundProps {
  [key: string]: unknown;
}

export interface PortfolioProps {
  [key: string]: unknown;
}

export interface ProjectCardProps {
  [key: string]: unknown;
}

export interface ProjectsSectionProps {
  [key: string]: unknown;
}

export interface ProjectViewerProps {
  [key: string]: unknown;
}

export interface RandomFactsProps {
  [key: string]: unknown;
  maxNotes?: number;
  refreshInterval?: number;
}

export interface RouteProps {
  [key: string]: unknown;
}

export interface SectionTitleProps {
  [key: string]: unknown;
  accent?: string;
  align?: 'center' | 'start';
  anchor?: string;
  text?: string;
}

export interface SelectProps {
  [key: string]: unknown;
  disabled?: boolean;
  label?: string;
  multiple?: boolean;
  onOptionSelect?: (...args: unknown[]) => unknown;
  options?: unknown[];
  visibleProp?: string;
}

export interface StudyCardProps {
  [key: string]: unknown;
}

export interface SwitchProps {
  [key: string]: unknown;
  checked?: boolean;
  customColor?: string;
  disabled?: boolean;
  label?: string;
  labelPlacement?: 'left' | 'right' | 'top' | 'bottom';
  toggle?: (...args: unknown[]) => unknown;
}

export interface TabsProps {
  [key: string]: unknown;
}

export interface TeachingSectionProps {
  [key: string]: unknown;
  accentColor?: string;
  animationDelay?: number;
  primaryColor?: string;
  secondaryColor?: string;
  showStudentProjects?: boolean;
  subjects?: unknown[];
  subtitle?: string;
  title?: string;
}

export interface TechExpertiseProps {
  [key: string]: unknown;
  marqueeSpeed?: number;
  showPauseButton?: boolean;
  subtitle?: string;
  title?: string;
}

export interface TechnicalSkillsSectionProps {
  [key: string]: unknown;
}

export interface TheImposterGameProps {
  [key: string]: unknown;
}

export interface ThemeSelectorProps {
  [key: string]: unknown;
}

export interface TimelineProps {
  [key: string]: unknown;
}

export interface ToolTipProps {
  [key: string]: unknown;
}

export interface TreeItemProps {
  [key: string]: unknown;
  items?: unknown[];
  onClickCallback?: (...args: unknown[]) => unknown;
  path?: string;
  value?: string;
}

export interface TreeViewProps {
  [key: string]: unknown;
  items?: unknown[];
  onClickCallback?: (...args: unknown[]) => unknown;
}

export interface WhatIsSliceProps {
  [key: string]: unknown;
}

export interface WordRevealProps {
  [key: string]: unknown;
  category?: string;
  imposters?: number;
  names?: unknown[];
  players?: number;
  word?: string;
}

export interface SliceComponentPropsMap {
  AboutSection: AboutSectionProps;
  Animations: AnimationsProps;
  AnimationsProvider: AnimationsProviderProps;
  BackgroundAudioToggle: BackgroundAudioToggleProps;
  BadgeCarousel: BadgeCarouselProps;
  BuiltWithBadge: BuiltWithBadgeProps;
  Button: ButtonProps;
  Card: CardProps;
  CategoryManagerModal: CategoryManagerModalProps;
  CertificateCard: CertificateCardProps;
  Charts: ChartsProps;
  Checkbox: CheckboxProps;
  ClickSoundToggle: ClickSoundToggleProps;
  CodeVisualizer: CodeVisualizerProps;
  ConfirmationModal: ConfirmationModalProps;
  Details: DetailsProps;
  DomPurify: DomPurifyProps;
  DropDown: DropDownProps;
  EducationSection: EducationSectionProps;
  ElementCarrousel: ElementCarrouselProps;
  ExperienceCard: ExperienceCardProps;
  ExperienceSection: ExperienceSectionProps;
  FetchManager: FetchManagerProps;
  GameFlow: GameFlowProps;
  GameSetup: GameSetupProps;
  Grid: GridProps;
  Icon: IconProps;
  Image: ImageProps;
  ImageCarrousel: ImageCarrouselProps;
  ImageDemo: ImageDemoProps;
  ImposterGameContextService: ImposterGameContextServiceProps;
  IndexedDbManager: IndexedDbManagerProps;
  Input: InputProps;
  Layout: LayoutProps;
  Link: LinkProps;
  Loading: LoadingProps;
  LocalStorageManager: LocalStorageManagerProps;
  MainMenu: MainMenuProps;
  MultiRoute: MultiRouteProps;
  MyNavigation: MyNavigationProps;
  NameManagerModal: NameManagerModalProps;
  Navbar: NavbarProps;
  NotFound: NotFoundProps;
  Portfolio: PortfolioProps;
  ProjectCard: ProjectCardProps;
  ProjectsSection: ProjectsSectionProps;
  ProjectViewer: ProjectViewerProps;
  RandomFacts: RandomFactsProps;
  Route: RouteProps;
  SectionTitle: SectionTitleProps;
  Select: SelectProps;
  StudyCard: StudyCardProps;
  Switch: SwitchProps;
  Tabs: TabsProps;
  TeachingSection: TeachingSectionProps;
  TechExpertise: TechExpertiseProps;
  TechnicalSkillsSection: TechnicalSkillsSectionProps;
  TheImposterGame: TheImposterGameProps;
  ThemeSelector: ThemeSelectorProps;
  Timeline: TimelineProps;
  ToolTip: ToolTipProps;
  TreeItem: TreeItemProps;
  TreeView: TreeViewProps;
  WhatIsSlice: WhatIsSliceProps;
  WordReveal: WordRevealProps;
}

export type SliceComponentName = keyof SliceComponentPropsMap;
export type SliceDynamicElement = HTMLElement & Record<string, any>;

declare global {
  const slice: SliceBuildApi & Record<string, any>;

  interface Event {
    detail: any;
    key: any;
    request: any;
    waitUntil: any;
    respondWith: any;
    target: any;
    currentTarget: any;
  }

  interface Element {
    querySelector<E extends Element = HTMLElement>(selectors: string): E | null;
    querySelectorAll<E extends Element = HTMLElement>(selectors: string): NodeListOf<E>;
  }
  interface HTMLElement {
    [key: string]: any;
  }
  interface EventTarget {
    [key: string]: any;
  }

  interface SliceBuildApi {
    build<K extends SliceComponentName>(
      name: K,
      props?: SliceComponentPropsMap[K]
    ): Promise<SliceDynamicElement | null>;
  }
}

declare module 'slicejs-web-framework' {
  interface SliceApi {
    build<K extends SliceComponentName>(
      name: K,
      props?: SliceComponentPropsMap[K]
    ): Promise<SliceDynamicElement | null>;
    getComponent<T extends SliceDynamicElement = SliceDynamicElement>(
      componentSliceId: string
    ): T | undefined;
  }
}

export {};
